
# User models location
env:
  path: components/

workspace:
  path: workspace/

# Database settings
db:
  influx:
    address: localhost
    port: 8087
    dbname: demkit
    username: iecon
    password: Wd%WMHQIvT0tweVyWynO
    token: 4Kfrb4jxdppFVuG%vnEiVv%Ec11XBugi2Sr16pGR
    org: iecon

# IECON parameters
spb_domain: SERENE

mqtt_spb:
  address: localhost
  port: 1882
  username: iecon
  password: fVB3b53fNTqGkJa%edMu

# Application path
app_path: /usr/lib/iecon/application/iecon_app_demkit

# Variable output for logs ans backups (stored within the workspace folder of a model by default)
# Do not forget the traling slash!
var:
  backup: var/backup/
  databasebackup: var/backup/database/
  log: var/log/

# Timezone information
timezonestr: Europe/Amsterdam


# OPTIONAL SETTINGS
# These settings are only required for certain cases and normally can remain unchanged

# Socket path for networked configurations
network:
  sockPath: ipc:///home/user/python/

#Smart house config
smarthouse:
  usb: /dev/ttyACM0

# STATIC SETTINGS
# You should not modify lines below

# Version control, this config is valid for V4 of DEMKit
ver: 4.1
